# Generated by Django 3.2 on 2021-08-17 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210817_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='post',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment')},
        ),
    ]
