# Generated by Django 3.2 on 2021-08-17 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210817_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='comment',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='blog',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'blog')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'blog')},
        ),
    ]
